[package]
name = "expiring-bloom-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
bitvec = "1.0.1"
fnv = "1.0.7"
murmur3 = "0.5.2"
redb = "2.1.3"
serde = { version = "1.0.210", features = ["derive"] }

[dev-dependencies]
rand = "0.8.5"
