[package]
name = "expiring-bloom-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1"
bitvec = "1"
fnv = "1"
murmur3 = "0.5"
async-trait = "0.1"
serde = { version = "1", features = ["derive"] }
redb = { version = "2", optional = true }
rustis = { version = "0.13", features = ["tokio-runtime"], optional = true }
thiserror = "2"
tokio = { version = "1.42.0", features = ["full"] }

[dev-dependencies]
rand = "0.8"
expiring-bloom-rs = { path = ".", features = [] }

[features]
redis = ["dep:rustis"]
redb = ["dep:redb"]
