[package]
name = "expiring-bloom-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1"
bitvec = "1"
fnv = "1"
murmur3 = "0.5"
serde = { version = "1", features = ["derive"] }
redb = { version = "2", optional = true }
rustis = { version = "0.13", features = ["tokio-runtime"], optional = true }
async-trait = { version = "0.1", optional = true }

[dev-dependencies]
rand = "0.8.5"
expiring-bloom-rs = { path = ".", features = ["redis"] }


[features]
redis = ["dep:rustis", "dep:async-trait"]
redb = ["dep:redb"]
