[package]
name = "expiring-bloom-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1"
bitvec = "1"
fnv = "1"
murmur3 = "0.5"
thiserror = "2"
redb = { version = "2", optional = true }
derive_builder = "0.20"
dotenvy = "0.15"

[dev-dependencies]
rand = "0.8"
expiring-bloom-rs = { path = ".", features = ["redb"] }
criterion = { version = "0.5", features = ["html_reports"] }

[features]
redb = ["dep:redb"]

[[bench]]
name = "bloom_benchmarks"
harness = false
